### ISSUE TITLE
First look feedback

### ISSUE THREAD

**Issue by xaur** [0x5826/blog.dcrclub.org#2]
Hi all, @Guang168 shared the link to this repo in chat. Great to see this effort to organize CN content in Git!

Pasting some rough feedback from first look:

* remove macOS-specific `.DS_Store` files and add them to gitin ([github docs](https://help.github.com/articles/ignoring-files/), [git docs](https://git-scm.com/docs/gitignore))
* [front page](https://blog.dcrclub.org/) does not have navigation except the "Next" link at the bottom
* please recommend `https://explorer.dcrdata.org/` as the primary block explorer link, `https://mainnet.decred.org/` is the old and ugly Insight explorer that is getting phased out. Either don't recommend it at all or at least position it as a secondary/backup.
* `dcr.observer` "richlist" website was criticized many times in chat for not being accurate. I don't have quick references at hand, you can search in matrix/riot logs. If that doesn't work let me know I'll dig my archives.
* Markdown files do not follow a consistent naming pattern

Not sure about this one but will note it:

* structure to separate by chapters might be sub optimal but it's hard to tell without knowing how chapters are called. For a book that would work. For a blog not so much (for a blog I would recommend a plain list of files named `YYYYMMDD-name-of-the-post-lowercase.md`)

**Comment by Guang168** [comment]
removed DS store with commit  bca44436550b92a762b083cecea9003a108d22a7
updated rec explorer links with commit 4263eaa642f9692e7aa6d7cd2b91cbe5723498c5

@xaur do you have recommended replacement site for "richlist" ?
