### ISSUE TITLE
[指引] 如何加入 Matrix 上的中文聊天室

### ISSUE THREAD

**Issue by morphymore** [0x5826/blog.dcrclub.org#4]
DCR Chinese 聊天室連結：https://matrix.to/#/!nUWpVrwhlJFyLuMlGw:decred.org?via=decred.org&via=matrix.org

<img width="1440" alt="matrix_decred_01" src="https://user-images.githubusercontent.com/13583235/53480160-91bbb400-3ab5-11e9-8e29-2b95b4234720.png">
<img width="1440" alt="matrix_decred_02" src="https://user-images.githubusercontent.com/13583235/53480166-941e0e00-3ab5-11e9-9841-6123993c8af1.png">
<img width="1440" alt="matrix_decred_03_04" src="https://user-images.githubusercontent.com/13583235/53480173-97b19500-3ab5-11e9-9ddb-2f81fb975c19.png">
<img width="1440" alt="matrix_decred_05" src="https://user-images.githubusercontent.com/13583235/53480179-9a13ef00-3ab5-11e9-8c88-fb0b7e7fbfd0.png">

**Comment by Guang168** [comment]
Added in commit 6d9d33725774c975c1934503747a912cd8057a2b
